# DB config
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:40521/railway
spring.datasource.username=root
spring.datasource.password=kdHdrnvnrLvBodIZpoXCocvxACYfcvea

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=hirex_super_secret_key_change_in_production_2024
app.jwt.expiration=86400000

# Render Port (Render sets PORT env var)
server.port=${PORT:8080}

# Allowed origins for CORS (used in SecurityConfig)
cors.allowed.origins=https://job-portal-frontend-avtp.onrender.com
